'use client';
import {useRouter} from 'next/navigation';import {useRecordDraft,useMutation,SaveFeedback} from './draft-state';import type {MutationResult} from '@/lib/crm/types';
export type EditorRecord={id:string;version:number;[key:string]:unknown};
export type Field={name:string;label:string;type?:'text'|'date'|'checkbox';required?:boolean;options?:{value:string;label:string}[];max?:number;hint?:string;locked?:boolean};
export function RecordForm({record,fields,save,label,decorate,createdHref}:{record:EditorRecord;fields:Field[];save:(input:Record<string,unknown>,version:number|null,requestId:string)=>Promise<MutationResult<EditorRecord>>;label:string;decorate?:(record:EditorRecord)=>EditorRecord;createdHref?:string}){
 const {draft,edit,accept,receive,rebase,reload}=useRecordDraft(record);const m=useMutation<EditorRecord>();const router=useRouter();const isNew=record.id==='new';
 async function commit(reapply=false){const d=reapply?rebase():draft;if(reapply)m.changed();const input=Object.fromEntries(fields.map(f=>[f.name,d.value[f.name]??(f.type==='checkbox'?false:'')]));if(!isNew)input.id=d.value.id;const result=await m.run(r=>save(input,isNew?null:d.base.version,r));if(result?.ok){accept(isNew?record:decorate?decorate(result.value):result.value);if(isNew&&createdHref)router.push(createdHref+result.value.id);}else if(result?.kind==='conflict'&&result.current)receive(decorate?decorate(result.current):result.current);}
 return <form className="owner-form" onSubmit={e=>{e.preventDefault();void commit();}}><fieldset className="owner-form-grid" disabled={m.pending}>{fields.map(f=>f.type==='checkbox'?<label className="owner-check" key={f.name}><input type="checkbox" checked={Boolean(draft.value[f.name])} onChange={e=>{edit({[f.name]:e.target.checked});m.changed();}}/>{f.label}</label>:<label className="owner-field" key={f.name}>{f.label}{f.options?<select required={f.required} disabled={f.locked&&!isNew} value={String(draft.value[f.name]??'')} onChange={e=>{edit({[f.name]:e.target.value});m.changed();}}>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input type={f.type??'text'} required={f.required} maxLength={f.max??300} value={String(draft.value[f.name]??'')} onChange={e=>{edit({[f.name]:e.target.value});m.changed();}}/>}{f.hint?<small>{f.hint}</small>:null}</label>)}</fieldset>{draft.incoming?<div className="owner-error" role="alert">Another owner changed this record. Your draft is preserved.<details><summary>View saved values</summary><pre className="owner-diff">{JSON.stringify(draft.incoming,null,2)}</pre></details><div className="owner-actions"><button type="button" className="owner-button owner-button-secondary" onClick={reload}>Use saved version</button><button type="button" className="owner-button" disabled={m.pending} onClick={()=>void commit(true)}>Reapply my changes</button></div></div>:null}<SaveFeedback result={m.result}/><button className="owner-button" disabled={m.pending||Boolean(draft.incoming)}>{m.pending?'Saving…':label}</button></form>;
}
